FROM node:18

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY . .

RUN npm install
RUN npx prisma generate

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]

